### ISSUE TITLE
Connection string without password - Out of Range exception.

### ISSUE THREAD

**Issue by piter10p** [FoundatioFx/Foundatio.Storage.SshNet#5]
[SshNetFileStorage.cs:252](https://github.com/FoundatioFx/Foundatio.Storage.SshNet/blob/f3c285cfff9a617436425d3170c05b28e98997c1/src/Foundatio.Storage.SshNet/Storage/SshNetFileStorage.cs#L252)

```
string[] userParts = uri.UserInfo.Split(new [] { ':' }, StringSplitOptions.RemoveEmptyEntries);
string username = Uri.UnescapeDataString(userParts.First());
string password = Uri.UnescapeDataString(userParts.Length > 0 ? userParts[1] : String.Empty);
```

In the case, when user is using connection string without password (for example, when authenticating via ssh keys), this code causes [System.IndexOutOfRangeException](https://docs.microsoft.com/dotnet/api/system.indexoutofrangeexception?view=netcore-3.0).

**Comment by piter10p** [comment]
Created [pull request](https://github.com/FoundatioFx/Foundatio.Storage.SshNet/pull/6) with bugfix.

**Comment by niemyjski** [comment]
Thanks for the pr :)
